# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftests', '0002_band_showband_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drftests.Venue'),
        ),
    ]
