# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drftests', '0003_show_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showband',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='band',
            name='shows',
            field=models.ManyToManyField(to='drftests.Show'),
        ),
        migrations.AddField(
            model_name='show',
            name='bands',
            field=models.ManyToManyField(to='drftests.Band'),
        ),
    ]
